### PR TITLE
UPDATE: Navbar and Loading Screen

### PR DESCRIPTION
**Pull request by Farhaduneci**
- Navbar positioning enhanced and looks smooth now, it also were not fixed on other pages than home, which is fixed now.
- Loading screen animation is also updated and has PasteMe text on it now.

### CODE REVIEW

**Comment by lnxpy** [comment]
Navbar fix is alright. Thanks for fixing it. We need more changes for the loading splash screen though.

**Comment by Farhaduneci** [comment]
The loading screen is now updated, with PasteMe logo pulsing at the center of the page. Very minimal :D

**Comment by lnxpy** [comment]
@Farhaduneci, It sounds nice! Please merge the first and last commits into one so that we can merge this PR. :)

**Review by lnxpy — APPROVED** [review]

**Comment by Farhaduneci** [comment]
That's done, I believe.

**Comment by Farhaduneci** [comment]
There were some issues doing so, opened a new PR on #98

**Pull request closed without merging**
